/*************************************************************
 * FriendService.h
 * Generated by corpc framework corpc_gen.py
 * Create Time: 2022-12-24 08:41:49
 * This file will not be overwrite althrough protobuf file changed !!!
 * Just write this file while not exist
*************************************************************/


#include <google/protobuf/service.h>
#include <corpc/common/start.h>
#include "FriendService/service/FriendService.h"


int main(int argc, char* argv[])
{
    if (argc != 2) {
        printf("Start FriendService server error, input argc is not 2!");
        printf("Start FriendService like this: \n");
        printf("./FriendService FriendService.yml\n");
        return 0;
    }

    corpc::initConfig(argv[1]);

    REGISTER_SERVICE(FriendService::FriendServiceRpcImpl);

    corpc::startServer();
    
    return 0;
}