/*************************************************************
 * test_login_client.cpp
 * Generated by corpc framework corpc_gen.py
 * Create Time: 2022-12-17 11:24:33
 * This file will not be overwrite althrough protobuf file changed !!!
 * Just write this file while not exist
 *************************************************************/

#include <google/protobuf/service.h>
#include <corpc/net/pb/pb_rpc_client_block_channel.h>
#include <corpc/net/pb/pb_rpc_controller.h>
#include <corpc/net/pb/pb_rpc_closure.h>
#include <corpc/net/net_address.h>
#include <corpc/common/start.h>
#include "UserService/pb/UserService.pb.h"

void testClient()
{
    corpc::IPAddress::ptr addr = std::make_shared<corpc::IPAddress>("0.0.0.0", 39999);

    corpc::PbRpcClientBlockChannel channel(addr);
    UserServiceRpc_Stub stub(&channel);

    corpc::PbRpcController rpcController;
    rpcController.SetTimeout(5000);

    ::LoginRequest rpcReq;
    ::LoginResponse rpcRes;

    std::cout << "Send to UserService server " << addr->toString() << ", request body: " << rpcReq.ShortDebugString() << std::endl;
    stub.Login(&rpcController, &rpcReq, &rpcRes, NULL);

    if (rpcController.ErrorCode() != 0) {
        std::cout << "Failed to call UserService server, error code: " << rpcController.ErrorCode() << ", error info: " << rpcController.ErrorText() << std::endl;
        return;
    }

    std::cout << "Success get response from UserService server " << addr->toString() << ", response body: " << rpcRes.ShortDebugString() << std::endl;
}

int main(int argc, char *argv[])
{
    if (argc != 2) {
        printf("Start UserService test client error, input argc is not 2!");
        printf("Start UserService like this: \n");
        printf("./test_login_client UserService.yml\n");
        return 0;
    }

    corpc::initConfig(argv[1]);

    testClient();

    return 0;
}