/*************************************************************
 * MessageService.h
 * Generated by corpc framework corpc_gen.py
 * Create Time: 2023-01-10 10:20:34
 * This file will not be overwrite althrough protobuf file changed !!!
 * Just write this file while not exist
*************************************************************/


#include <google/protobuf/service.h>
#include <corpc/common/start.h>
#include "MessageService/service/MessageService.h"


int main(int argc, char* argv[])
{
    if (argc != 2) {
        printf("Start MessageService server error, input argc is not 2!");
        printf("Start MessageService like this: \n");
        printf("./MessageService MessageService.yml\n");
        return 0;
    }

    corpc::initConfig(argv[1]);

    REGISTER_SERVICE(MessageService::MessageServiceRpcImpl);

    corpc::startServer();
    
    return 0;
}