/*************************************************************
 * login.cpp
 * Generated by corpc framework corpc_gen.py
 * Create Time: 2022-12-17 11:24:33
 * This file will not be overwrite althrough protobuf file changed !!!
 * Just write this file while not exist
*************************************************************/

#include <corpc/common/log.h>
#include "UserService/interface/login.h"
#include "UserService/pb/UserService.pb.h"


namespace UserService {

LoginInterface::LoginInterface(const ::LoginRequest &request, ::LoginReponse &response)
    : request_(request), 
    response_(response)
{

}

LoginInterface::~LoginInterface()
{

}

void LoginInterface::run()
{
    //
    // Run your business at here
    // response_.set_ret_code(0);
    // response_.set_res_info("Succ");
    //

}

}