/*************************************************************
 * logout.cpp
 * Generated by corpc framework corpc_gen.py
 * Create Time: 2022-12-17 11:24:33
 * This file will not be overwrite althrough protobuf file changed !!!
 * Just write this file while not exist
*************************************************************/

#include <corpc/common/log.h>
#include "UserService/interface/logout.h"
#include "UserService/pb/UserService.pb.h"
#include "UserService/dao/user_dao.h"
#include "UserService/common/business_exception.h"
#include "UserService/common/error_code.h"
#include "UserService/common/const.h"


namespace UserService {

LogoutInterface::LogoutInterface(const ::LogoutRequest &request, ::LogoutResponse &response)
    : request_(request), 
    response_(response)
{

}

LogoutInterface::~LogoutInterface()
{

}

void LogoutInterface::run()
{
    //
    // Run your business at here
    // response_.set_ret_code(0);
    // response_.set_res_info("Succ");
    //
    int id = request_.user_id();
    UserDao dao;
    User user = dao.queryState(id);
    if (user.getState() != ONLINE_STATE) {
        throw BusinessException(ACCOUNT_LOGGED_OUT, getErrorMsg(ACCOUNT_LOGGED_OUT), __FILE__, __LINE__);
    }
    if (!dao.updateState(user)) {
        // 注销失败
        throw BusinessException(LOGOUT_FAILED, getErrorMsg(LOGOUT_FAILED), __FILE__, __LINE__);
    }
}

}