/*************************************************************
 * logout.h
 * Generated by corpc framework corpc_gen.py
 * Create Time: 2022-12-17 11:24:33
 * This file will not be overwrite althrough protobuf file changed !!!
 * Just write this file while not exist
*************************************************************/

#ifndef USERSERVICE_INTERFACE_LOGOUT_H
#define USERSERVICE_INTERFACE_LOGOUT_H 

#include "UserService/pb/UserService.pb.h"


namespace UserService {

/**
 * Rpc Interface Class
 * Alloc one object every time RPC call begin, and destroy this object while RPC call end
*/

class LogoutInterface {
public:
    LogoutInterface(const ::LogoutRequest& request, ::LogoutResponse& response);
    ~LogoutInterface();

    void run(); // Business implementation

private:
    const ::LogoutRequest& request_;      // request object from client
    ::LogoutResponse& response_;          // response object that reply to client
};

}

#endif