/*************************************************************
 * get_group_users.h
 * Generated by corpc framework corpc_gen.py
 * Create Time: 2022-12-30 10:15:13
 * This file will not be overwrite althrough protobuf file changed !!!
 * Just write this file while not exist
*************************************************************/

#ifndef GROUPSERVICE_INTERFACE_GET_GROUP_USERS_H
#define GROUPSERVICE_INTERFACE_GET_GROUP_USERS_H 

#include "GroupService/pb/GroupService.pb.h"


namespace GroupService {

/**
 * Rpc Interface Class
 * Alloc one object every time RPC call begin, and destroy this object while RPC call end
*/

class GetGroupUsersInterface {
public:
    GetGroupUsersInterface(const ::GetGroupUsersRequest& request, ::GetGroupUsersResponse& response);
    ~GetGroupUsersInterface();

    void run(); // Business implementation

private:
    const ::GetGroupUsersRequest& request_;      // request object from client
    ::GetGroupUsersResponse& response_;          // response object that reply to client
};

}

#endif