/*************************************************************
 * get_group_info.h
 * Generated by corpc framework corpc_gen.py
 * Create Time: 2022-12-31 09:55:47
 * This file will not be overwrite althrough protobuf file changed !!!
 * Just write this file while not exist
*************************************************************/

#ifndef GROUPSERVICE_INTERFACE_GET_GROUP_INFO_H
#define GROUPSERVICE_INTERFACE_GET_GROUP_INFO_H 

#include "GroupService/pb/GroupService.pb.h"


namespace GroupService {

/**
 * Rpc Interface Class
 * Alloc one object every time RPC call begin, and destroy this object while RPC call end
*/

class GetGroupInfoInterface {
public:
    GetGroupInfoInterface(const ::GetGroupInfoRequest& request, ::GetGroupInfoResponse& response);
    ~GetGroupInfoInterface();

    void run(); // Business implementation

private:
    const ::GetGroupInfoRequest& request_;      // request object from client
    ::GetGroupInfoResponse& response_;          // response object that reply to client
};

}

#endif