/*************************************************************
 * UserService.h
 * Generated by corpc framework corpc_gen.py
 * Create Time: 2023-01-08 18:12:23
 * This file will be overwrite every time
*************************************************************/

#ifndef USERSERVICE_SERVICE_USERSERVICE_H 
#define USERSERVICE_SERVICE_USERSERVICE_H

#include <google/protobuf/service.h>
#include "UserService/pb/UserService.pb.h"


namespace UserService {

class UserServiceRpcImpl : public UserServiceRpc {
public:
    UserServiceRpcImpl() = default;
    ~UserServiceRpcImpl() = default;

    // override from UserServiceRpc
    virtual void Login(::google::protobuf::RpcController* controller,
                       const ::LoginRequest* request,
                       ::LoginResponse* response,
                       ::google::protobuf::Closure* done);

    // override from UserServiceRpc
    virtual void Register(::google::protobuf::RpcController* controller,
                       const ::RegisterRequest* request,
                       ::RegisterResponse* response,
                       ::google::protobuf::Closure* done);

    // override from UserServiceRpc
    virtual void Logout(::google::protobuf::RpcController* controller,
                       const ::LogoutRequest* request,
                       ::LogoutResponse* response,
                       ::google::protobuf::Closure* done);

};

}

#endif