/*************************************************************
 * save_offline_message.cpp
 * Generated by corpc framework corpc_gen.py
 * Create Time: 2023-01-16 11:02:51
 * This file will not be overwrite althrough protobuf file changed !!!
 * Just write this file while not exist
*************************************************************/

#include <corpc/common/log.h>
#include "ChatService/interface/save_offline_message.h"
#include "ChatService/pb/ChatService.pb.h"


namespace ChatService {

SaveOfflineMessageInterface::SaveOfflineMessageInterface(const ::SaveOfflineMessageRequest &request, ::SaveOfflineMessageResponse &response)
    : request_(request), 
    response_(response)
{

}

SaveOfflineMessageInterface::~SaveOfflineMessageInterface()
{

}

void SaveOfflineMessageInterface::run()
{
    //
    // Run your business at here
    // response_.set_ret_code(0);
    // response_.set_res_info("Succ");
    //

}

}