/*************************************************************
 * FriendService.h
 * Generated by corpc framework corpc_gen.py
 * Create Time: 2022-12-24 08:41:49
 * This file will be overwrite every time
*************************************************************/

#ifndef FRIENDSERVICE_SERVICE_FRIENDSERVICE_H 
#define FRIENDSERVICE_SERVICE_FRIENDSERVICE_H

#include <google/protobuf/service.h>
#include "FriendService/pb/FriendService.pb.h"


namespace FriendService {

class FriendServiceRpcImpl : public FriendServiceRpc {
public:
    FriendServiceRpcImpl() = default;
    ~FriendServiceRpcImpl() = default;

    // override from FriendServiceRpc
    virtual void GetFriendList(::google::protobuf::RpcController* controller,
                       const ::FriendListRequest* request,
                       ::FriendListResponse* response,
                       ::google::protobuf::Closure* done);

    // override from FriendServiceRpc
    virtual void GetUserInfo(::google::protobuf::RpcController* controller,
                       const ::UserInfoRequest* request,
                       ::UserInfoResponse* response,
                       ::google::protobuf::Closure* done);

    // override from FriendServiceRpc
    virtual void AddFriend(::google::protobuf::RpcController* controller,
                       const ::AddFriendRequest* request,
                       ::AddFriendResponse* response,
                       ::google::protobuf::Closure* done);

    // override from FriendServiceRpc
    virtual void DeleteFriend(::google::protobuf::RpcController* controller,
                       const ::DeleteFriendRequest* request,
                       ::DeleteFriendResponse* response,
                       ::google::protobuf::Closure* done);

};

}

#endif