/*************************************************************
 * get_user_info.cpp
 * Generated by corpc framework corpc_gen.py
 * Create Time: 2022-12-24 08:41:49
 * This file will not be overwrite althrough protobuf file changed !!!
 * Just write this file while not exist
*************************************************************/

#include <corpc/common/log.h>
#include "FriendService/interface/get_user_info.h"
#include "FriendService/pb/FriendService.pb.h"
#include "FriendService/dao/user_dao.h"
#include "FriendService/common/business_exception.h"
#include "FriendService/common/error_code.h"


namespace FriendService {

GetUserInfoInterface::GetUserInfoInterface(const ::UserInfoRequest &request, ::UserInfoResponse &response)
    : request_(request), 
    response_(response)
{

}

GetUserInfoInterface::~GetUserInfoInterface()
{

}

void GetUserInfoInterface::run()
{
    //
    // Run your business at here
    // response_.set_ret_code(0);
    // response_.set_res_info("Succ");
    //
    int userid = request_.id();
    UserDao dao;
    User user = dao.queryInfo(userid);
    if (user.getState() == "not_exist") {
        throw BusinessException(ACCOUNT_NOT_EXIST, getErrorMsg(ACCOUNT_NOT_EXIST), __FILE__, __LINE__);
    }
    response_.set_id(user.getId());
    response_.set_name(user.getName());
    response_.set_state(user.getState());
}

}